export type LangCode =
  | "hi" | "ta" | "te" | "bn" | "mr" | "kn" | "ml" | "gu"
  | "pa" | "or" | "as" | "bho" | "raj" | "hr" | "en";

export interface Language {
  code: LangCode;
  name: string;
  english: string;
  promptName: string;
}

export const LANGUAGES: Language[] = [
  { code: "hi",  name: "हिन्दी",    english: "Hindi",       promptName: "Hindi in Devanagari script" },
  { code: "ta",  name: "தமிழ்",     english: "Tamil",       promptName: "Tamil in Tamil script" },
  { code: "te",  name: "తెలుగు",    english: "Telugu",      promptName: "Telugu in Telugu script" },
  { code: "bn",  name: "বাংলা",     english: "Bengali",     promptName: "Bengali in Bangla script" },
  { code: "mr",  name: "मराठी",     english: "Marathi",     promptName: "Marathi in Devanagari script" },
  { code: "kn",  name: "ಕನ್ನಡ",     english: "Kannada",     promptName: "Kannada in Kannada script" },
  { code: "ml",  name: "മലയാളം",   english: "Malayalam",   promptName: "Malayalam in Malayalam script" },
  { code: "gu",  name: "ગુજરાતી",   english: "Gujarati",    promptName: "Gujarati in Gujarati script" },
  { code: "pa",  name: "ਪੰਜਾਬੀ",    english: "Punjabi",     promptName: "Punjabi in Gurmukhi script" },
  { code: "or",  name: "ଓଡ଼ିଆ",     english: "Odia",        promptName: "Odia in Odia script" },
  { code: "as",  name: "অসমীয়া",   english: "Assamese",    promptName: "Assamese in Assamese script" },
  { code: "bho", name: "भोजपुरी",   english: "Bhojpuri",    promptName: "Bhojpuri in Devanagari script" },
  { code: "raj", name: "राजस्थानी",  english: "Rajasthani",  promptName: "Rajasthani in Devanagari script" },
  { code: "hr",  name: "हरियाणवी",  english: "Haryanvi",    promptName: "Haryanvi in Devanagari script" },
  { code: "en",  name: "English",   english: "English",     promptName: "English" },
];

export function getLang(code: LangCode): Language {
  return LANGUAGES.find((l) => l.code === code) ?? LANGUAGES[0];
}

// UI strings for each language
export type UIStrings = {
  liveLabel: string;
  heroTitle: string;
  heroSub: string;
  aiPowered: string;
  reload: string;
  loading: string;
  all: string;
  noTrends: string;
  footer: string;
  trendNotFound: string;
  goHome: string;
  trending: string;
  heatScore: string;
  posts: string;
  region: string;
  allIndia: string;
  signalSources: string;
  aiSummary: string;
  whyTrending: string;
  topPosts: string;
  postOnTrend: string;
};

const UI: Record<LangCode, UIStrings> = {
  hi: {
    liveLabel: "लाइव ट्रेंड्स",
    heroTitle: "आज भारत क्या\nबात कर रहा है?",
    heroSub: "AI-संचालित",
    aiPowered: "AI-संचालित",
    reload: "फिर से लोड करें",
    loading: "लोड हो रहा है…",
    all: "सभी",
    noTrends: "इस श्रेणी में कोई ट्रेंड नहीं",
    footer: "Powered by Lovable AI",
    trendNotFound: "ट्रेंड नहीं मिला",
    goHome: "होम पर जाएँ",
    trending: "ट्रेंडिंग",
    heatScore: "हीट स्कोर",
    posts: "पोस्ट्स",
    region: "क्षेत्र",
    allIndia: "अखिल भारत",
    signalSources: "सिग्नल स्रोत",
    aiSummary: "AI सारांश",
    whyTrending: "क्यों ट्रेंड कर रहा है",
    topPosts: "टॉप पोस्ट्स",
    postOnTrend: "इस ट्रेंड पर पोस्ट करें ✨",
  },
  ta: {
    liveLabel: "லைவ் ட்ரெண்ட்ஸ்",
    heroTitle: "இன்று இந்தியா\nஎன்ன பேசுகிறது?",
    heroSub: "AI-இயக்கம்",
    aiPowered: "AI-இயக்கம்",
    reload: "மீண்டும் ஏற்று",
    loading: "ஏற்றுகிறது…",
    all: "அனைத்தும்",
    noTrends: "இந்த வகையில் ட்ரெண்ட் இல்லை",
    footer: "Powered by Lovable AI",
    trendNotFound: "ட்ரெண்ட் கிடைக்கவில்லை",
    goHome: "முகப்புக்கு செல்",
    trending: "ட்ரெண்டிங்",
    heatScore: "வெப்ப மதிப்பெண்",
    posts: "பதிவுகள்",
    region: "பகுதி",
    allIndia: "அகில இந்தியா",
    signalSources: "சமிக்ஞை ஆதாரங்கள்",
    aiSummary: "AI சுருக்கம்",
    whyTrending: "ஏன் ட்ரெண்டிங்",
    topPosts: "சிறந்த பதிவுகள்",
    postOnTrend: "இந்த ட்ரெண்டில் போஸ்ட் செய் ✨",
  },
  te: {
    liveLabel: "లైవ్ ట్రెండ్స్",
    heroTitle: "ఈ రోజు భారతదేశం\nఏమి మాట్లాడుతోంది?",
    heroSub: "AI-ఆధారిత",
    aiPowered: "AI-ఆధారిత",
    reload: "మళ్ళీ లోడ్ చేయండి",
    loading: "లోడ్ అవుతోంది…",
    all: "అన్నీ",
    noTrends: "ఈ వర్గంలో ట్రెండ్‌లు లేవు",
    footer: "Powered by Lovable AI",
    trendNotFound: "ట్రెండ్ కనుగొనబడలేదు",
    goHome: "హోమ్‌కు వెళ్ళండి",
    trending: "ట్రెండింగ్",
    heatScore: "హీట్ స్కోర్",
    posts: "పోస్ట్‌లు",
    region: "ప్రాంతం",
    allIndia: "అఖిల భారతం",
    signalSources: "సిగ్నల్ మూలాలు",
    aiSummary: "AI సారాంశం",
    whyTrending: "ఎందుకు ట్రెండ్ అవుతోంది",
    topPosts: "టాప్ పోస్ట్‌లు",
    postOnTrend: "ఈ ట్రెండ్‌పై పోస్ట్ చేయండి ✨",
  },
  bn: {
    liveLabel: "লাইভ ট্রেন্ডস",
    heroTitle: "আজ ভারত\nকী নিয়ে কথা বলছে?",
    heroSub: "AI-চালিত",
    aiPowered: "AI-চালিত",
    reload: "আবার লোড করুন",
    loading: "লোড হচ্ছে…",
    all: "সব",
    noTrends: "এই বিভাগে কোনো ট্রেন্ড নেই",
    footer: "Powered by Lovable AI",
    trendNotFound: "ট্রেন্ড পাওয়া যায়নি",
    goHome: "হোমে যান",
    trending: "ট্রেন্ডিং",
    heatScore: "হিট স্কোর",
    posts: "পোস্ট",
    region: "অঞ্চল",
    allIndia: "সমগ্র ভারত",
    signalSources: "সিগন্যাল উৎস",
    aiSummary: "AI সারাংশ",
    whyTrending: "কেন ট্রেন্ডিং",
    topPosts: "টপ পোস্ট",
    postOnTrend: "এই ট্রেন্ডে পোস্ট করুন ✨",
  },
  mr: {
    liveLabel: "लाइव्ह ट्रेंड्स",
    heroTitle: "आज भारत\nकशावर बोलतोय?",
    heroSub: "AI-चालित",
    aiPowered: "AI-चालित",
    reload: "पुन्हा लोड करा",
    loading: "लोड होत आहे…",
    all: "सर्व",
    noTrends: "या श्रेणीत कोणतेही ट्रेंड नाही",
    footer: "Powered by Lovable AI",
    trendNotFound: "ट्रेंड सापडला नाही",
    goHome: "होमवर जा",
    trending: "ट्रेंडिंग",
    heatScore: "हीट स्कोर",
    posts: "पोस्ट्स",
    region: "प्रदेश",
    allIndia: "अखिल भारत",
    signalSources: "सिग्नल स्रोत",
    aiSummary: "AI सारांश",
    whyTrending: "का ट्रेंड होतोय",
    topPosts: "टॉप पोस्ट्स",
    postOnTrend: "या ट्रेंडवर पोस्ट करा ✨",
  },
  kn: {
    liveLabel: "ಲೈವ್ ಟ್ರೆಂಡ್ಸ್",
    heroTitle: "ಇಂದು ಭಾರತ\nಏನು ಮಾತನಾಡುತ್ತಿದೆ?",
    heroSub: "AI-ಚಾಲಿತ",
    aiPowered: "AI-ಚಾಲಿತ",
    reload: "ಮತ್ತೆ ಲೋಡ್ ಮಾಡಿ",
    loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ…",
    all: "ಎಲ್ಲಾ",
    noTrends: "ಈ ವರ್ಗದಲ್ಲಿ ಟ್ರೆಂಡ್ ಇಲ್ಲ",
    footer: "Powered by Lovable AI",
    trendNotFound: "ಟ್ರೆಂಡ್ ಕಂಡುಬರಲಿಲ್ಲ",
    goHome: "ಹೋಮ್‌ಗೆ ಹೋಗಿ",
    trending: "ಟ್ರೆಂಡಿಂಗ್",
    heatScore: "ಹೀಟ್ ಸ್ಕೋರ್",
    posts: "ಪೋಸ್ಟ್‌ಗಳು",
    region: "ಪ್ರದೇಶ",
    allIndia: "ಅಖಿಲ ಭಾರತ",
    signalSources: "ಸಿಗ್ನಲ್ ಮೂಲಗಳು",
    aiSummary: "AI ಸಾರಾಂಶ",
    whyTrending: "ಏಕೆ ಟ್ರೆಂಡಿಂಗ್",
    topPosts: "ಟಾಪ್ ಪೋಸ್ಟ್‌ಗಳು",
    postOnTrend: "ಈ ಟ್ರೆಂಡ್‌ನಲ್ಲಿ ಪೋಸ್ಟ್ ಮಾಡಿ ✨",
  },
  ml: {
    liveLabel: "ലൈവ് ട്രെൻഡ്സ്",
    heroTitle: "ഇന്ന് ഭാരതം\nഎന്താണ് പറയുന്നത്?",
    heroSub: "AI-പവേർഡ്",
    aiPowered: "AI-പവേർഡ്",
    reload: "വീണ്ടും ലോഡ് ചെയ്യുക",
    loading: "ലോഡ് ചെയ്യുന്നു…",
    all: "എല്ലാം",
    noTrends: "ഈ വിഭാഗത്തിൽ ട്രെൻഡ് ഇല്ല",
    footer: "Powered by Lovable AI",
    trendNotFound: "ട്രെൻഡ് കണ്ടെത്തിയില്ല",
    goHome: "ഹോമിലേക്ക് പോകുക",
    trending: "ട്രെൻഡിംഗ്",
    heatScore: "ഹീറ്റ് സ്കോർ",
    posts: "പോസ്റ്റുകൾ",
    region: "പ്രദേശം",
    allIndia: "അഖില ഭാരതം",
    signalSources: "സിഗ്നൽ ഉറവിടങ്ങൾ",
    aiSummary: "AI സംഗ്രഹം",
    whyTrending: "എന്തുകൊണ്ട് ട്രെൻഡിംഗ്",
    topPosts: "ടോപ് പോസ്റ്റുകൾ",
    postOnTrend: "ഈ ട്രെൻഡിൽ പോസ്റ്റ് ചെയ്യൂ ✨",
  },
  gu: {
    liveLabel: "લાઇવ ટ્રેન્ડ્સ",
    heroTitle: "આજે ભારત\nશું વાત કરે છે?",
    heroSub: "AI-સંચાલિત",
    aiPowered: "AI-સંચાલિત",
    reload: "ફરી લોડ કરો",
    loading: "લોડ થઈ રહ્યું છે…",
    all: "બધા",
    noTrends: "આ શ્રેણીમાં કોઈ ટ્રેન્ડ નથી",
    footer: "Powered by Lovable AI",
    trendNotFound: "ટ્રેન્ડ મળ્યો નથી",
    goHome: "હોમ પર જાઓ",
    trending: "ટ્રેન્ડિંગ",
    heatScore: "હીટ સ્કોર",
    posts: "પોસ્ટ્સ",
    region: "પ્રદેશ",
    allIndia: "અખિલ ભારત",
    signalSources: "સિગ્નલ સ્ત્રોત",
    aiSummary: "AI સારાંશ",
    whyTrending: "શા માટે ટ્રેન્ડ છે",
    topPosts: "ટોપ પોસ્ટ્સ",
    postOnTrend: "આ ટ્રેન્ડ પર પોસ્ટ કરો ✨",
  },
  pa: {
    liveLabel: "ਲਾਈਵ ਟ੍ਰੈਂਡਸ",
    heroTitle: "ਅੱਜ ਭਾਰਤ\nਕੀ ਗੱਲ ਕਰ ਰਿਹਾ ਹੈ?",
    heroSub: "AI-ਸੰਚਾਲਿਤ",
    aiPowered: "AI-ਸੰਚਾਲਿਤ",
    reload: "ਦੁਬਾਰਾ ਲੋਡ ਕਰੋ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…",
    all: "ਸਭ",
    noTrends: "ਇਸ ਸ਼੍ਰੇਣੀ ਵਿੱਚ ਕੋਈ ਟ੍ਰੈਂਡ ਨਹੀਂ",
    footer: "Powered by Lovable AI",
    trendNotFound: "ਟ੍ਰੈਂਡ ਨਹੀਂ ਮਿਲਿਆ",
    goHome: "ਹੋਮ ਤੇ ਜਾਓ",
    trending: "ਟ੍ਰੈਂਡਿੰਗ",
    heatScore: "ਹੀਟ ਸਕੋਰ",
    posts: "ਪੋਸਟਾਂ",
    region: "ਖੇਤਰ",
    allIndia: "ਸਮੁੱਚਾ ਭਾਰਤ",
    signalSources: "ਸਿਗਨਲ ਸ੍ਰੋਤ",
    aiSummary: "AI ਸਾਰ",
    whyTrending: "ਕਿਉਂ ਟ੍ਰੈਂਡ ਹੋ ਰਿਹਾ",
    topPosts: "ਟਾਪ ਪੋਸਟਾਂ",
    postOnTrend: "ਇਸ ਟ੍ਰੈਂਡ ਤੇ ਪੋਸਟ ਕਰੋ ✨",
  },
  or: {
    liveLabel: "ଲାଇଭ ଟ୍ରେଣ୍ଡସ",
    heroTitle: "ଆଜି ଭାରତ\nକ'ଣ କଥା ହେଉଛି?",
    heroSub: "AI-ଚାଳିତ",
    aiPowered: "AI-ଚାଳିତ",
    reload: "ପୁନର୍ବାର ଲୋଡ୍ କରନ୍ତୁ",
    loading: "ଲୋଡ୍ ହେଉଛି…",
    all: "ସମସ୍ତ",
    noTrends: "ଏହି ବିଭାଗରେ କୌଣସି ଟ୍ରେଣ୍ଡ ନାହିଁ",
    footer: "Powered by Lovable AI",
    trendNotFound: "ଟ୍ରେଣ୍ଡ ମିଳିଲା ନାହିଁ",
    goHome: "ହୋମକୁ ଯାଆନ୍ତୁ",
    trending: "ଟ୍ରେଣ୍ଡିଂ",
    heatScore: "ହିଟ୍ ସ୍କୋର",
    posts: "ପୋଷ୍ଟ",
    region: "ଅଞ୍ଚଳ",
    allIndia: "ସମଗ୍ର ଭାରତ",
    signalSources: "ସିଗନାଲ ଉତ୍ସ",
    aiSummary: "AI ସାରାଂଶ",
    whyTrending: "କାହିଁକି ଟ୍ରେଣ୍ଡିଂ",
    topPosts: "ଟପ ପୋଷ୍ଟ",
    postOnTrend: "ଏହି ଟ୍ରେଣ୍ଡରେ ପୋଷ୍ଟ କରନ୍ତୁ ✨",
  },
  as: {
    liveLabel: "লাইভ ট্ৰেণ্ডচ",
    heroTitle: "আজি ভাৰত\nকি কৈছে?",
    heroSub: "AI-চালিত",
    aiPowered: "AI-চালিত",
    reload: "আকৌ লোড কৰক",
    loading: "লোড হৈ আছে…",
    all: "সকলো",
    noTrends: "এই শ্ৰেণীত কোনো ট্ৰেণ্ড নাই",
    footer: "Powered by Lovable AI",
    trendNotFound: "ট্ৰেণ্ড পোৱা নগ'ল",
    goHome: "হোমলৈ যাওক",
    trending: "ট্ৰেণ্ডিং",
    heatScore: "হিট স্কোৰ",
    posts: "পোষ্ট",
    region: "অঞ্চল",
    allIndia: "সমগ্ৰ ভাৰত",
    signalSources: "সংকেত উৎস",
    aiSummary: "AI সাৰাংশ",
    whyTrending: "কিয় ট্ৰেণ্ডিং",
    topPosts: "টপ পোষ্ট",
    postOnTrend: "এই ট্ৰেণ্ডত পোষ্ট কৰক ✨",
  },
  bho: {
    liveLabel: "लाइव ट्रेंड्स",
    heroTitle: "आज भारत\nका बात कर रहल बा?",
    heroSub: "AI-संचालित",
    aiPowered: "AI-संचालित",
    reload: "फेर से लोड करीं",
    loading: "लोड हो रहल बा…",
    all: "सब",
    noTrends: "इ श्रेणी में कवनो ट्रेंड नइखे",
    footer: "Powered by Lovable AI",
    trendNotFound: "ट्रेंड ना मिलल",
    goHome: "होम पर जाईं",
    trending: "ट्रेंडिंग",
    heatScore: "हीट स्कोर",
    posts: "पोस्ट्स",
    region: "क्षेत्र",
    allIndia: "पूरा भारत",
    signalSources: "सिग्नल स्रोत",
    aiSummary: "AI सारांश",
    whyTrending: "काहे ट्रेंड हो रहल बा",
    topPosts: "टॉप पोस्ट्स",
    postOnTrend: "इ ट्रेंड पर पोस्ट करीं ✨",
  },
  raj: {
    liveLabel: "लाइव ट्रेंड्स",
    heroTitle: "आज भारत\nकाई बात कर रह्यो है?",
    heroSub: "AI-संचालित",
    aiPowered: "AI-संचालित",
    reload: "फेर लोड करो",
    loading: "लोड हो रह्यो है…",
    all: "सगला",
    noTrends: "इ श्रेणी में कोई ट्रेंड कोनी",
    footer: "Powered by Lovable AI",
    trendNotFound: "ट्रेंड कोनी मिल्यो",
    goHome: "होम पर जाओ",
    trending: "ट्रेंडिंग",
    heatScore: "हीट स्कोर",
    posts: "पोस्ट्स",
    region: "प्रदेश",
    allIndia: "पूरो भारत",
    signalSources: "सिग्नल स्रोत",
    aiSummary: "AI सारांश",
    whyTrending: "काई ट्रेंड हो रह्यो",
    topPosts: "टॉप पोस्ट्स",
    postOnTrend: "इ ट्रेंड पर पोस्ट करो ✨",
  },
  hr: {
    liveLabel: "लाइव ट्रेंड्स",
    heroTitle: "आज भारत\nके बारै में बात हो रही?",
    heroSub: "AI-संचालित",
    aiPowered: "AI-संचालित",
    reload: "दुबारा लोड करो",
    loading: "लोड हो रहा…",
    all: "सारे",
    noTrends: "इस श्रेणी में कोई ट्रेंड कोनी",
    footer: "Powered by Lovable AI",
    trendNotFound: "ट्रेंड नहीं मिला",
    goHome: "होम पै जा",
    trending: "ट्रेंडिंग",
    heatScore: "हीट स्कोर",
    posts: "पोस्ट्स",
    region: "क्षेत्र",
    allIndia: "सारा भारत",
    signalSources: "सिग्नल स्रोत",
    aiSummary: "AI सारांश",
    whyTrending: "क्यूं ट्रेंड हो रहा",
    topPosts: "टॉप पोस्ट्स",
    postOnTrend: "इस ट्रेंड पै पोस्ट करो ✨",
  },
  en: {
    liveLabel: "LIVE TRENDS",
    heroTitle: "What is India\ntalking about today?",
    heroSub: "AI-powered",
    aiPowered: "AI-powered",
    reload: "Reload",
    loading: "Loading…",
    all: "All",
    noTrends: "No trends in this category",
    footer: "Powered by Lovable AI",
    trendNotFound: "Trend not found",
    goHome: "Go Home",
    trending: "Trending",
    heatScore: "Heat Score",
    posts: "Posts",
    region: "Region",
    allIndia: "All India",
    signalSources: "Signal Sources",
    aiSummary: "AI Summary",
    whyTrending: "Why Trending",
    topPosts: "Top Posts",
    postOnTrend: "Post on this trend ✨",
  },
};

export function getUI(code: LangCode): UIStrings {
  return UI[code] ?? UI.hi;
}
